[programs.localnet]
transfer_token = "CyW3dajTAaoH4oh2q75DbX7PcvN92dR6JiMVeVQc783Y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ngoanpv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
